name: Trigger auto deployment for fil4r

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fil4r-AutoDeployTrigger-152942c7-b6bc-4b33-9860-2395a669c3e8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FIL4R_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FIL4R_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FIL4R_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.FIL4R_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIL4R_REGISTRY_PASSWORD }}
          containerAppName: fil4r
          resourceGroup: fil4r_group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


